FROM node:20-alpine AS builder
WORKDIR /app

# Build arg para la URL del API (Nginx proxy → /api/v1)
ARG VITE_API_URL=""
ENV VITE_API_URL=$VITE_API_URL

COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
